[package]
name = "tauri-plugin-google-app-functions-macros"
description = "Procedural macros for tauri-plugin-google-app-functions"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
keywords = ["tauri", "tauri-plugin", "android", "app-functions"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
