//! Expose Rust functions of a Tauri app as Android
//! [AppFunctions](https://developer.android.com/ai/appfunctions), so on-device agents can
//! discover and call them.
//!
//! ```ignore
//! use tauri_plugin_google_app_functions::{app_function, app_function_serializable, AppFunctionError};
//!
//! /// A note stored in the app.
//! #[app_function_serializable]
//! pub struct Note {
//!   /// Unique note ID.
//!   pub id: String,
//!   /// Note text.
//!   pub text: String,
//! }
//!
//! /// Creates a note.
//! ///
//! /// # Arguments
//! /// * `text` - The note text.
//! #[app_function]
//! async fn create_note(text: String) -> Result<Note, AppFunctionError> {
//!   Ok(Note { id: "1".into(), text })
//! }
//! ```
//!
//! The AppFunctions schema the system indexes is generated by
//! `tauri-plugin-google-app-functions-build` from the app's `build.rs`.

use tauri::{
  Runtime,
  plugin::{Builder, TauriPlugin},
};

pub use registry::{AppFunctionError, app_handle, invoke, registered_functions};
pub use tauri_plugin_google_app_functions_macros::{app_function, app_function_serializable};

#[cfg(target_os = "android")]
mod android;

mod error;
mod registry;

pub use error::{Error, Result};

#[doc(hidden)]
pub mod __private {
  pub use inventory;
  pub use serde;
  pub use serde_json;

  pub use crate::registry::{
    AppFunctionEntry, BoxFuture, invalid_arguments, serialize_output, serialize_result,
  };
}

/// Initializes the plugin. It hands the app's [`tauri::AppHandle`] to app functions that take
/// one.
pub fn init<R: Runtime>() -> TauriPlugin<R> {
  Builder::new("google-app-functions")
    .setup(|app, _api| {
      registry::set_app_handle(app.clone());
      Ok(())
    })
    .build()
}
