//! Expose Rust functions of a Tauri app as Android
//! [AppFunctions](https://developer.android.com/ai/appfunctions), so on-device agents can
//! discover and call them.
//!
//! ```ignore
//! use tauri_plugin_google_app_functions::{app_function, app_function_serializable, AppFunctionError};
//!
//! /// A note stored in the app.
//! #[app_function_serializable]
//! pub struct Note {
//!   /// Unique note ID.
//!   pub id: String,
//!   /// Note text.
//!   pub text: String,
//! }
//!
//! /// Creates a note.
//! ///
//! /// # Arguments
//! /// * `text` - The note text.
//! #[app_function]
//! async fn create_note(text: String) -> Result<Note, AppFunctionError> {
//!   Ok(Note { id: "1".into(), text })
//! }
//! ```
//!
//! The AppFunctions schema the system indexes is generated by
//! `tauri-plugin-google-app-functions-build` from the app's `build.rs`.

use tauri::{
  plugin::{Builder, TauriPlugin},
  Manager, Runtime,
};

pub use models::*;
pub use registry::{app_handle, invoke, registered_functions, AppFunctionError};
pub use tauri_plugin_google_app_functions_macros::{app_function, app_function_serializable};

#[cfg(desktop)]
mod desktop;
#[cfg(mobile)]
mod mobile;
#[cfg(target_os = "android")]
mod android;

mod commands;
mod error;
mod models;
mod registry;

pub use error::{Error, Result};

#[cfg(desktop)]
use desktop::GoogleAppFunctions;
#[cfg(mobile)]
use mobile::GoogleAppFunctions;

#[doc(hidden)]
pub mod __private {
  pub use inventory;
  pub use serde;
  pub use serde_json;

  pub use crate::registry::{
    invalid_arguments, serialize_output, serialize_result, AppFunctionEntry, BoxFuture,
  };
}

/// Extensions to [`tauri::App`], [`tauri::AppHandle`] and [`tauri::Window`] to access the google-app-functions APIs.
pub trait GoogleAppFunctionsExt<R: Runtime> {
  fn google_app_functions(&self) -> &GoogleAppFunctions<R>;
}

impl<R: Runtime, T: Manager<R>> crate::GoogleAppFunctionsExt<R> for T {
  fn google_app_functions(&self) -> &GoogleAppFunctions<R> {
    self.state::<GoogleAppFunctions<R>>().inner()
  }
}

/// Initializes the plugin.
pub fn init<R: Runtime>() -> TauriPlugin<R> {
  Builder::new("google-app-functions")
    .invoke_handler(tauri::generate_handler![commands::ping])
    .setup(|app, api| {
      #[cfg(mobile)]
      let google_app_functions = mobile::init(app, api)?;
      #[cfg(desktop)]
      let google_app_functions = desktop::init(app, api)?;
      app.manage(google_app_functions);
      registry::set_app_handle(app.clone());
      Ok(())
    })
    .build()
}
